### QUESTION 1
#1. Matrix Operation
Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]
a. A+B
b. AB
c. 3A−2B

In [1]:
import numpy as np

In [4]:
#QUESTION-1A
A = np.array([[2,-1],
              [0,3]])
B = np.array([[1,2],
              [-3,4]])
print(A+B)


[[ 3  1]
 [-3  7]]


In [3]:
#QUESTION-1B
A = np.array([[2,-1],
              [0,3]])
B = np.array([[1,2],
              [-3,4]])
print(A @ B)


[[ 5  0]
 [-9 12]]


In [2]:
#QUESTION-1C
A = np.array([[2,-1],
              [0,3]])
B = np.array([[1,2],
              [-3,4]])
print(3*A-2*B)

[[ 4 -7]
 [ 6  1]]


### QUESTION 2
#Determinants and Inverses  
Find the determinant of A.
Determine whether A is invertible. If yes, calculate A−1

In [9]:
#QUESTION-2A
d= round(np.linalg.det(A),2)
print(f"determinant of matrix A is {d}")


determinant of matrix A is 6.0


In [7]:
#QUESTION-2B
d= round(np.linalg.det(A),2)
if(not d==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


### QUESTION 3
#Eigenvalues and Eigenvectors  
Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]

In [12]:
C = np.array([[4,1],
              [-2,1]])
eigval,eigvec = np.linalg.eig(A)
print(f"eigen values of matrix A is {eigval}")
print(f"eigen vectors of matrix A is {eigvec}")

eigen values of matrix A is [2. 3.]
eigen vectors of matrix A is [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


### QUESTION 4
#You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1:,x1: 4,x2:  1.5,x3: 100 and price: 20
car 2:,x1: 6,x2:  2.0,x3: 150 and price: 30
Then, find the price of a car 3 with features:x1: 8,x2:  3.0,x3: 200,price:?
Hints:
1-Represent the given dataset as a matrix equation X.T*β=y, where X is the feature matrix, β is the coefficient vector, and y is the price vector  
2-Compute β (the coefficients) using the normal equation:β=(X.T * X)^−1  X.T y
where,
X.T --> transpose matrix

In [13]:
S= np.array([[4,1.5,100],
              [6,2.0,150]])
P = np.array([[20],
              [30]])
inv = np.linalg.pinv(S.T @ S)
B = inv @ S.T @ P
X = np.array([[8,3.0,200]])
pri= np.linalg.det(X @ B)
print(f" price of the car X3 is {pri}")

 price of the car X3 is 40.00000000000243
